# Generated by Django 2.1.7 on 2019-03-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='news',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='parents',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
