# Generated by Django 2.1.7 on 2019-03-15 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20190315_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('author', models.ForeignKey(help_text='评论作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论作者')),
                ('news', models.ForeignKey(help_text='评论新闻', on_delete=django.db.models.deletion.CASCADE, to='news.NewsModel', verbose_name='评论新闻')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.CommentModel')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'db_table': 'tb_comments',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
