# Generated by Django 2.1.7 on 2019-03-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsbanner',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newshots',
            name='news',
        ),
        migrations.DeleteModel(
            name='NewsBanner',
        ),
        migrations.DeleteModel(
            name='NewsHots',
        ),
    ]
