# Generated by Django 2.1.7 on 2019-03-15 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190315_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('image_url', models.URLField(help_text='轮播图图片链接', verbose_name='轮播图图片链接')),
                ('priority', models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], default=6, help_text='轮播图片优先级', verbose_name='轮播图片优先级')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsModel')),
            ],
            options={
                'verbose_name': '新闻轮播图',
                'verbose_name_plural': '新闻轮播图',
                'db_table': 'news_banner',
                'ordering': ['priority', '-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsHots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='逻辑删除')),
                ('priority', models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级')], default=3, help_text='新闻优先级', verbose_name='新闻优先级')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.NewsModel')),
            ],
            options={
                'verbose_name': '新闻优先级',
                'verbose_name_plural': '新闻优先级',
                'db_table': 'tb_news_hots',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
